# Generated by Django 3.2.9 on 2022-02-08 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_by', models.TextField()),
                ('sent_on', models.DateTimeField(default=datetime.datetime.now)),
                ('msg', models.TextField()),
                ('sent_to_room', models.TextField()),
            ],
        ),
    ]
