# Generated by Django 3.2.9 on 2022-02-12 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_on',
            field=models.TextField(default=datetime.datetime.now),
        ),
    ]
